<?php

namespace Database\Seeders;

use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'product_category_id' => 1,
                'supplier_id' => 1,
                'sku' => 'CPU-001',
                'varcode' => '100000000001',
                'product_name' => 'Intel Core i5-12400',
                'description' => '12th Gen Desktop Processor',
                'cost_price' => 9500,
                'selling_price' => 10999,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 2,
                'supplier_id' => 2,
                'sku' => 'MB-001',
                'varcode' => '100000000002',
                'product_name' => 'ASUS Prime B760M-K',
                'description' => 'Intel LGA1700 Motherboard',
                'cost_price' => 5200,
                'selling_price' => 6100,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 3,
                'supplier_id' => 3,
                'sku' => 'RAM-001',
                'varcode' => '100000000003',
                'product_name' => 'Kingston Fury Beast 16GB DDR4',
                'description' => '3200MHz Gaming Memory',
                'cost_price' => 1800,
                'selling_price' => 2300,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 4,
                'supplier_id' => 4,
                'sku' => 'SSD-001',
                'varcode' => '100000000004',
                'product_name' => 'Samsung 970 EVO Plus 500GB',
                'description' => 'NVMe SSD',
                'cost_price' => 2700,
                'selling_price' => 3400,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 5,
                'supplier_id' => 5,
                'sku' => 'HDD-001',
                'varcode' => '100000000005',
                'product_name' => 'Seagate Barracuda 1TB',
                'description' => '3.5 SATA Hard Drive',
                'cost_price' => 1800,
                'selling_price' => 2400,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 6,
                'supplier_id' => 6,
                'sku' => 'GPU-001',
                'varcode' => '100000000006',
                'product_name' => 'MSI RTX 4060 Ventus 8GB',
                'description' => 'Gaming Graphics Card',
                'cost_price' => 18500,
                'selling_price' => 21500,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 7,
                'supplier_id' => 7,
                'sku' => 'PSU-001',
                'varcode' => '100000000007',
                'product_name' => 'Corsair CV650',
                'description' => '650W 80+ Bronze PSU',
                'cost_price' => 2500,
                'selling_price' => 3200,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 8,
                'supplier_id' => 8,
                'sku' => 'CASE-001',
                'varcode' => '100000000008',
                'product_name' => 'InPlay Meteor 03',
                'description' => 'ATX Gaming Case',
                'cost_price' => 1200,
                'selling_price' => 1700,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 9,
                'supplier_id' => 9,
                'sku' => 'MON-001',
                'varcode' => '100000000009',
                'product_name' => 'HKC 24" 165Hz Monitor',
                'description' => 'IPS Gaming Monitor',
                'cost_price' => 6200,
                'selling_price' => 7500,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 10,
                'supplier_id' => 10,
                'sku' => 'KB-001',
                'varcode' => '100000000010',
                'product_name' => 'Redragon K552',
                'description' => 'Mechanical Keyboard',
                'cost_price' => 1400,
                'selling_price' => 1900,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 11,
                'supplier_id' => 11,
                'sku' => 'MS-001',
                'varcode' => '100000000011',
                'product_name' => 'Logitech G102',
                'description' => 'Gaming Mouse',
                'cost_price' => 800,
                'selling_price' => 1100,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 12,
                'supplier_id' => 12,
                'sku' => 'HS-001',
                'varcode' => '100000000012',
                'product_name' => 'Razer BlackShark V2 X',
                'description' => 'Gaming Headset',
                'cost_price' => 1900,
                'selling_price' => 2500,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 13,
                'supplier_id' => 13,
                'sku' => 'SPK-001',
                'varcode' => '100000000013',
                'product_name' => 'Logitech Z213',
                'description' => '2.1 Multimedia Speakers',
                'cost_price' => 1300,
                'selling_price' => 1800,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 14,
                'supplier_id' => 14,
                'sku' => 'WB-001',
                'varcode' => '100000000014',
                'product_name' => 'A4Tech HD Webcam',
                'description' => '1080P USB Camera',
                'cost_price' => 950,
                'selling_price' => 1400,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Unavailable',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 15,
                'supplier_id' => 15,
                'sku' => 'PR-001',
                'varcode' => '100000000015',
                'product_name' => 'Epson L3210',
                'description' => 'All-in-One Ink Tank Printer',
                'cost_price' => 7600,
                'selling_price' => 8900,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 16,
                'supplier_id' => 16,
                'sku' => 'UPS-001',
                'varcode' => '100000000016',
                'product_name' => 'Secure UPS 650VA',
                'description' => 'Power Backup',
                'cost_price' => 1800,
                'selling_price' => 2400,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 17,
                'supplier_id' => 17,
                'sku' => 'NET-001',
                'varcode' => '100000000017',
                'product_name' => 'TP-Link Archer C64',
                'description' => 'Dual Band WiFi Router',
                'cost_price' => 1700,
                'selling_price' => 2300,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 18,
                'supplier_id' => 18,
                'sku' => 'CBL-001',
                'varcode' => '100000000018',
                'product_name' => 'UGREEN HDMI Cable 2M',
                'description' => 'HDMI 2.0 Cable',
                'cost_price' => 180,
                'selling_price' => 350,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 19,
                'supplier_id' => 19,
                'sku' => 'USB-001',
                'varcode' => '100000000019',
                'product_name' => 'SanDisk Ultra 64GB',
                'description' => 'USB 3.0 Flash Drive',
                'cost_price' => 350,
                'selling_price' => 550,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_category_id' => 20,
                'supplier_id' => 20,
                'sku' => 'LAP-001',
                'varcode' => '100000000020',
                'product_name' => 'Lenovo IdeaPad Slim 3',
                'description' => '15.6" Laptop',
                'cost_price' => 28500,
                'selling_price' => 32999,
                'image' => 'https://i0.wp.com/picjumbo.com/wp-content/uploads/detailed-shot-of-ripples-at-sunset-free-image.jpeg?w=600&quality=80',
                'status' => 'Available',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
